version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: ioredis
    versions:
    - 4.19.4
    - 4.20.0
    - 4.21.0
    - 4.22.0
    - 4.23.0
    - 4.23.1
    - 4.24.0
    - 4.24.1
    - 4.24.2
    - 4.24.3
    - 4.24.4
    - 4.24.5
    - 4.24.6
    - 4.25.0
    - 4.26.0
    - 4.27.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.0
    - 0.38.1
    - 0.38.2
  - dependency-name: mime-types
    versions:
    - 2.1.28
    - 2.1.29
